name: news
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Network Dependencies
  vexana: ^5.0.0

  # Core
  equatable: ^2.0.5
  kartal: ^4.0.4

  flutter_bloc: ^8.1.6

  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/images/
